# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33c767fa10f3c36baf26bf10ca724e0e2172638412a717661acb32b02b9c59440722353bfc003c0c6af46ca2a476dedd0bf8cba81c6f643a95c0ed138d2055d1

test:
  secret_key_base: c112b957399596c1e3105b7e78349b73ad71989456bdd1f8da21d0195ff5eeab6249a48dcf2e6df51bc1d46ac778f53ffbcd808c6fbf10750bb9cad35dc79009

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
